[FIXES] sched: ems: Fix the build
[fix-gcc-build]

Commit 2b4abb94fe76 ("sched: ems: introduce core sparing governor")
introduces wrong function signature, which leads to build error:

    kernel/sched/ems/sparing.c:90:13:
        error: function declaration isn't a prototype
        [-Werror=strict-prototypes]
            static bool ecs_update_system_status()
            ^~~~~~~~~~~~~~~~~~~~~~~~

Make that function to take void as a param to fix that.

Fixes: 2b4abb94fe76 ("sched: ems: introduce core sparing governor")
Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
Change-Id: Id12007f765e0762b7483839086ec238f8a253dd3