[FIXES] sched: Fix the build
[fix-gcc-build]

Commit f2e08e7c2a9b removes EMVv1.0, but leaves some garbage, which
breaks the build:

    ./include/linux/rcupdate.h:371:36:
        error: dereferencing pointer to incomplete type 'struct task_band'
    kernel/sched/core.c:2243:2:
        note: in expansion of macro 'rcu_assign_pointer'
            rcu_assign_pointer(p->band, NULL);
            ^~~~~~~~~~~~~~~~~~

Remove these leftovers to fix the build.

Fixes: f2e08e7c2a9b ("sched: support EMSv2.0")
Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
Change-Id: I28a7b5f6b22950824a8a684bf490f8a27eaefadc