[FIXES] soc: samsung: gnssif: Fix the build
[fix-gcc-build]

Fix next build error:

    drivers/soc/samsung/gnssif/pmu-gnss.c:145:13:
        error: function declaration isn't a prototype
        [-Werror=strict-prototypes]
            static bool check_apm_int_pending()

Fixes: 49d11a0e55d5 ("[COMMON] soc: samsung: gnssif: fix build error "unused variable 'intr_bid_pend'"")
Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
Change-Id: I7723236e3d92305ba02ee36e162aac58866461e9