[FIXES] treewide: Fix the build due to in-loop variable declaration
[fix-gcc-build]

Fix this build error (treewide):

    error: 'for' loop initial declarations are only allowed in
           C99 or C11 mode

Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
Change-Id: Ifc9b75ca75fb2350902e2882f874351503ac98b2